/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    events: Event;
    'event-templates': EventTemplate;
    team: Team;
    media: Media;
    categories: Category;
    contacts: Contact;
    members: Member;
    'membership-tiers': MembershipTier;
    orders: Order;
    'audit-log': AuditLog;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-templates': EventTemplatesSelect<false> | EventTemplatesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'membership-tiers': MembershipTiersSelect<false> | MembershipTiersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'minimal' | 'fullBleed';
    /**
     * The main heading displayed in the hero area.
     */
    heading?: string | null;
    /**
     * Heading + Subheading: two lines of text at different sizes. Single Text: one line at a comfortable reading size, no secondary text.
     */
    textLayout?: ('heading-subheading' | 'single-text') | null;
    /**
     * Optional secondary text below the heading.
     */
    subheading?: string | null;
    /**
     * Background image for the hero. Use a high-resolution landscape image.
     */
    media?: (number | null) | Media;
    /**
     * How dark the gradient overlay should be (0 = fully transparent, 100 = fully opaque). Default 50.
     */
    overlayOpacity?: number | null;
    /**
     * Up to 3 call-to-action buttons displayed below the heading.
     */
    ctaButtons?:
      | {
          variant: 'primary' | 'secondary' | 'accent' | 'outline';
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  layout: (
    | ContentBlock
    | ImageTextBlock
    | CardGridBlock
    | TextColumnsBlock
    | CallToActionBlock
    | CtaBannerBlock
    | EventsListBlock
    | NewsFeedBlock
    | TestimonialsBlock
    | SponsorsGridBlock
    | StatsBarBlock
    | IconGridBlock
    | MixedContentRowBlock
    | MembershipTiersBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | MapEmbedBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO (e.g., "Board members at the 2025 gala").
   */
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Main image displayed at the top of the post.
   */
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  layout: 'imageLeft' | 'imageRight';
  image: number | Media;
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  enableCta?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Number of columns on desktop. Stacks to fewer columns on smaller screens.
   */
  columns: '2' | '3' | '4';
  /**
   * Add cards to the grid
   */
  cards?:
    | {
        /**
         * Card image — displayed at the top of the card
         */
        image?: (number | null) | Media;
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextColumnsBlock".
 */
export interface TextColumnsBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Controls the column layout. On mobile, all layouts stack to a single column.
   */
  layout: 'oneColumn' | 'twoEqual' | 'twoWideLeft' | 'twoWideRight' | 'threeEqual' | 'fourEqual';
  /**
   * Add up to 4 columns of rich text content
   */
  columns?:
    | {
        richText: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  heading: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  /**
   * Visual style of the CTA button
   */
  ctaVariant?: ('primary' | 'secondary' | 'accent' | 'outline') | null;
  /**
   * Optional background image — will display with a dark overlay for text readability
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsListBlock".
 */
export interface EventsListBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Optional short paragraph below the heading
   */
  introText?: string | null;
  /**
   * Featured: only events marked as featured. Upcoming: future events by date. All: everything published.
   */
  displayMode: 'featured' | 'upcoming' | 'all';
  /**
   * Maximum number of events to display (1–12)
   */
  maxItems?: number | null;
  enableViewAllLink?: boolean | null;
  /**
   * Link to the full events listing page
   */
  viewAllLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsFeedBlock".
 */
export interface NewsFeedBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Optional short paragraph below the heading
   */
  introText?: string | null;
  /**
   * Maximum number of posts to display (1–12)
   */
  maxItems?: number | null;
  /**
   * Optional: only show posts from these categories. Leave empty to show all categories.
   */
  categoryFilter?: (number | Category)[] | null;
  enableViewAllLink?: boolean | null;
  /**
   * Link to the full news/blog listing page
   */
  viewAllLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsFeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Optional heading above the testimonials carousel
   */
  sectionHeading?: string | null;
  /**
   * Add testimonials — each one appears as a slide in the carousel
   */
  testimonials?:
    | {
        /**
         * A short, punchy excerpt displayed large — the "headline" of the testimonial
         */
        pullquote: string;
        /**
         * The complete testimonial text
         */
        fullQuote: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Name of the person giving the testimonial
         */
        attributionName: string;
        /**
         * Organization, title, or role — e.g., "Owner, Hudson Bay Trading Post"
         */
        attributionOrg?: string | null;
        /**
         * Optional headshot photo
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Automatically cycle through testimonials every 8 seconds
   */
  autoAdvance?: boolean | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorsGridBlock".
 */
export interface SponsorsGridBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Add sponsor tiers — e.g., "Pillar Partners", "Gold Sponsors"
   */
  tiers?:
    | {
        /**
         * Heading shown above this row of logos
         */
        tierName: string;
        /**
         * Grid shows all logos at once. Carousel lets you scroll through them with arrows.
         */
        displayMode: 'grid' | 'carousel';
        /**
         * Add sponsor logos with optional links to their websites
         */
        logos?:
          | {
              logo: number | Media;
              /**
               * Used for alt text and hover tooltip
               */
              sponsorName?: string | null;
              /**
               * Link to the sponsor's website (opens in new tab)
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sponsorsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarBlock".
 */
export interface StatsBarBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Add 2–6 statistics to display in a row
   */
  stats?:
    | {
        /**
         * The stat value — e.g., "500+", "$2M", "25 Years"
         */
        number: string;
        /**
         * Label below the number — e.g., "Active Members", "Raised Annually"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconGridBlock".
 */
export interface IconGridBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  columns: '2' | '3' | '4';
  items?:
    | {
        /**
         * Icon image — SVG recommended, displayed at 48×48px
         */
        icon: number | Media;
        /**
         * Small text above the heading (e.g., "Step 1", "Networking")
         */
        overline?: string | null;
        heading: string;
        /**
         * Short description — plain text, not rich text
         */
        body?: string | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MixedContentRowBlock".
 */
export interface MixedContentRowBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Vertical alignment of slot contents when heights differ
   */
  verticalAlignment?: ('top' | 'center' | 'bottom') | null;
  /**
   * Add 1–4 content slots. Column widths should add up to a sensible total.
   */
  slots?:
    | {
        width: 'quarter' | 'third' | 'half' | 'twoThirds' | 'threeQuarters' | 'full';
        contentType: 'richText' | 'image' | 'cta';
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        ctaHeading?: string | null;
        ctaBody?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mixedContentRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipTiersBlock".
 */
export interface MembershipTiersBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Optional intro paragraph displayed below the section heading.
   */
  introText?: string | null;
  /**
   * Optionally highlight one tier as "recommended" or "most popular". It will be visually emphasized.
   */
  highlightedTier?: (number | null) | MembershipTier;
  /**
   * Button text on each tier card (e.g., "Join Now", "Get Started").
   */
  ctaLabel?: string | null;
  /**
   * Where the tier card buttons link to — e.g., a contact page, application form, or member portal.
   */
  ctaLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'membershipTiers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers".
 */
export interface MembershipTier {
  id: number;
  /**
   * Tier name shown publicly (e.g., "Gold", "Platinum").
   */
  name: string;
  /**
   * Annual membership price. Enter in dollars (stored in minor units internally).
   */
  annualPrice: number;
  /**
   * Detailed tier description for the public-facing pricing page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * List of features/benefits included in this tier.
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls the order tiers appear on the pricing page. Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * Stripe Price ID for automated billing. Leave blank until Stripe integration is configured.
   */
  stripePriceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapEmbedBlock".
 */
export interface MapEmbedBlock {
  /**
   * Optional heading displayed above this section
   */
  sectionHeading?: string | null;
  /**
   * Address shown above/alongside the map.
   */
  address: string;
  /**
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Map zoom level (1-20).
   */
  zoom: number;
  /**
   * Optional short text shown beside the map (hours, directions, parking notes).
   */
  overlayText?: string | null;
  height?: ('320' | '420' | '520') | null;
  /**
   * Background color for this section
   */
  background?: ('default' | 'light' | 'dark' | 'brand' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional: choose a template to prefill ticketing, location, and other defaults on create.
   */
  eventTemplate?: (number | null) | EventTemplate;
  location: string;
  startDate: string;
  endDate: string;
  featuredImage?: (number | null) | Media;
  /**
   * Featured events appear prominently on the homepage and events page.
   */
  isFeatured?: boolean | null;
  /**
   * Uncheck for partner or community events hosted by other organizations.
   */
  isChambersEvent?: boolean | null;
  status: 'draft' | 'published' | 'cancelled';
  /**
   * Choose how attendance is handled for this event.
   */
  ticketingType: 'none' | 'free-registration' | 'external-link' | 'chamber-managed';
  /**
   * Use when ticket sales are handled on another platform.
   */
  externalTicketUrl?: string | null;
  /**
   * Maximum number of registrations. Leave blank for unlimited.
   */
  registrationCapacity?: number | null;
  ticketTypes?:
    | {
        name: string;
        description?: string | null;
        /**
         * Ticket price. Enter in dollars (stored in minor units internally).
         */
        price: number;
        capacity: number;
        saleStart?: string | null;
        saleEnd?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A small fee added to each ticket to cover platform costs. Leave as "None" if you don't want to charge extra.
   */
  serviceFee?: {
    feeType: 'none' | 'flat' | 'percentage';
    feeAmount?: number | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-templates".
 */
export interface EventTemplate {
  id: number;
  /**
   * A name for this recurring event series (e.g., "Monthly Luncheon", "AGM").
   */
  seriesName: string;
  defaultDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  defaultFeaturedImage?: (number | null) | Media;
  defaultLocation?: string | null;
  defaultTicketingType: 'none' | 'free-registration' | 'external-link' | 'chamber-managed';
  defaultExternalTicketUrl?: string | null;
  /**
   * Default max registrations. Leave blank for unlimited.
   */
  defaultRegistrationCapacity?: number | null;
  defaultTicketTypes?:
    | {
        name: string;
        description?: string | null;
        /**
         * Default ticket price. Enter in dollars (stored in minor units internally).
         */
        price: number;
        capacity: number;
        saleStart?: string | null;
        saleEnd?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default service fee applied to events created from this template.
   */
  defaultServiceFee?: {
    feeType: 'none' | 'flat' | 'percentage';
    feeAmount?: number | null;
  };
  defaultIsChambersEvent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  title: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  headshot?: (number | null) | Media;
  type: 'staff' | 'board';
  /**
   * Lower numbers appear first. Use this to control the order staff and board members are shown.
   */
  displayOrder: number;
  email?: string | null;
  /**
   * Full LinkedIn profile URL (e.g., https://linkedin.com/in/janedoe).
   */
  linkedin?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  /**
   * Full name of the person, or the organization name.
   */
  name: string;
  email?: string | null;
  phone?: string | null;
  /**
   * Is this contact a person or an organization? Members can be either type.
   */
  type: 'person' | 'organization';
  /**
   * If this person belongs to an organization, link the org Contact here.
   */
  organization?: (number | null) | Contact;
  address?: {
    street?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
  };
  /**
   * Flexible tags for categorizing contacts (e.g., vendor, municipal, media, prospect).
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full URL including https://
   */
  website?: string | null;
  socialLinks?: {
    facebook?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    x?: string | null;
  };
  /**
   * Internal notes about this contact. Not shown publicly.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Use column header filters to view members by status (e.g., "lapsed", "cancelled") or by tier. Click column headers to sort.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  title?: string | null;
  /**
   * The entity that IS the member — an organization or a person Contact.
   */
  contact: number | Contact;
  /**
   * The go-to human for this membership. Used when the member is an organization — link the main contact person here.
   */
  primaryContact?: (number | null) | Contact;
  /**
   * The membership tier this member is subscribed to.
   */
  membershipTier?: (number | null) | MembershipTier;
  /**
   * Membership status. In production, transitions should go through MembershipService for audit logging.
   */
  status: 'pending' | 'active' | 'lapsed' | 'cancelled' | 'reinstated';
  /**
   * Date the membership began.
   */
  joinedDate?: string | null;
  /**
   * Next renewal date for this membership.
   */
  renewalDate?: string | null;
  /**
   * Stripe Customer ID for billing integration.
   */
  stripeCustomerId?: string | null;
  /**
   * Xero Contact ID for accounting sync. Lives on the Member (the billable entity), not the Contact.
   */
  xeroContactId?: string | null;
  /**
   * Internal notes about this membership. Not visible to the member.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Full name of the person who made the purchase.
   */
  purchaserName: string;
  /**
   * Email for order confirmation and ticket delivery.
   */
  purchaserEmail: string;
  event: number | Event;
  /**
   * The ticket type identifier (matches ticketTypes.name on the event).
   */
  ticketType: string;
  quantity: number;
  /**
   * Optional link to a Contact record. Allows tracking purchase history for known contacts. Null for guest checkouts.
   */
  contact?: (number | null) | Contact;
  /**
   * Stripe Payment Intent ID. Indexed for idempotent webhook processing.
   */
  stripePaymentIntentId?: string | null;
  /**
   * Total charged amount (ticket price × quantity + service fee + tax). Stored in minor units.
   */
  totalAmount?: number | null;
  /**
   * Service fee amount, tracked separately for reporting. Stored in minor units.
   */
  serviceFeeAmount?: number | null;
  /**
   * Tax amount charged (e.g., HST), tracked separately for reporting. Stored in minor units.
   */
  taxAmount?: number | null;
  /**
   * Order status. Follows the state machine: pending → confirmed → refunded. In production, transitions go through OrderService (ADR-6).
   */
  status: 'pending' | 'confirmed' | 'refunded';
  /**
   * Auto-generated token for QR code ticket validation. Created when order is confirmed.
   */
  qrToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  entityType: 'member' | 'order' | 'payment' | 'contact';
  /**
   * ID of the entity this log entry relates to.
   */
  entityId: string;
  /**
   * What happened — e.g., "status_changed", "tier_upgraded", "payment_succeeded".
   */
  action: string;
  /**
   * Previous state (if applicable).
   */
  fromState?: string | null;
  /**
   * New state (if applicable).
   */
  toState?: string | null;
  /**
   * Who triggered this — staff user ID, Contact ID, "system", or "webhook".
   */
  actorId?: string | null;
  actorType: 'staff' | 'member' | 'system' | 'webhook';
  /**
   * Additional context as JSON (e.g., reason for override, payment details).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-templates';
        value: number | EventTemplate;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'membership-tiers';
        value: number | MembershipTier;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        heading?: T;
        textLayout?: T;
        subheading?: T;
        media?: T;
        overlayOpacity?: T;
        ctaButtons?:
          | T
          | {
              variant?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        textColumns?: T | TextColumnsBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        eventsList?: T | EventsListBlockSelect<T>;
        newsFeed?: T | NewsFeedBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        sponsorsGrid?: T | SponsorsGridBlockSelect<T>;
        statsBar?: T | StatsBarBlockSelect<T>;
        iconGrid?: T | IconGridBlockSelect<T>;
        mixedContentRow?: T | MixedContentRowBlockSelect<T>;
        membershipTiers?: T | MembershipTiersBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        mapEmbed?: T | MapEmbedBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  layout?: T;
  image?: T;
  heading?: T;
  body?: T;
  enableCta?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  columns?: T;
  cards?:
    | T
    | {
        image?: T;
        heading?: T;
        body?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextColumnsBlock_select".
 */
export interface TextColumnsBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  layout?: T;
  columns?:
    | T
    | {
        richText?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  ctaVariant?: T;
  backgroundImage?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsListBlock_select".
 */
export interface EventsListBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  introText?: T;
  displayMode?: T;
  maxItems?: T;
  enableViewAllLink?: T;
  viewAllLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsFeedBlock_select".
 */
export interface NewsFeedBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  introText?: T;
  maxItems?: T;
  categoryFilter?: T;
  enableViewAllLink?: T;
  viewAllLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  testimonials?:
    | T
    | {
        pullquote?: T;
        fullQuote?: T;
        attributionName?: T;
        attributionOrg?: T;
        photo?: T;
        id?: T;
      };
  autoAdvance?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorsGridBlock_select".
 */
export interface SponsorsGridBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  tiers?:
    | T
    | {
        tierName?: T;
        displayMode?: T;
        logos?:
          | T
          | {
              logo?: T;
              sponsorName?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarBlock_select".
 */
export interface StatsBarBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconGridBlock_select".
 */
export interface IconGridBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  columns?: T;
  items?:
    | T
    | {
        icon?: T;
        overline?: T;
        heading?: T;
        body?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MixedContentRowBlock_select".
 */
export interface MixedContentRowBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  verticalAlignment?: T;
  slots?:
    | T
    | {
        width?: T;
        contentType?: T;
        richText?: T;
        image?: T;
        ctaHeading?: T;
        ctaBody?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipTiersBlock_select".
 */
export interface MembershipTiersBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  introText?: T;
  highlightedTier?: T;
  ctaLabel?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapEmbedBlock_select".
 */
export interface MapEmbedBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  zoom?: T;
  overlayText?: T;
  height?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  eventTemplate?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  featuredImage?: T;
  isFeatured?: T;
  isChambersEvent?: T;
  status?: T;
  ticketingType?: T;
  externalTicketUrl?: T;
  registrationCapacity?: T;
  ticketTypes?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        capacity?: T;
        saleStart?: T;
        saleEnd?: T;
        id?: T;
      };
  serviceFee?:
    | T
    | {
        feeType?: T;
        feeAmount?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-templates_select".
 */
export interface EventTemplatesSelect<T extends boolean = true> {
  seriesName?: T;
  defaultDescription?: T;
  defaultFeaturedImage?: T;
  defaultLocation?: T;
  defaultTicketingType?: T;
  defaultExternalTicketUrl?: T;
  defaultRegistrationCapacity?: T;
  defaultTicketTypes?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        capacity?: T;
        saleStart?: T;
        saleEnd?: T;
        id?: T;
      };
  defaultServiceFee?:
    | T
    | {
        feeType?: T;
        feeAmount?: T;
      };
  defaultIsChambersEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  headshot?: T;
  type?: T;
  displayOrder?: T;
  email?: T;
  linkedin?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  type?: T;
  organization?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        province?: T;
        postalCode?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  website?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        linkedin?: T;
        instagram?: T;
        x?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  title?: T;
  contact?: T;
  primaryContact?: T;
  membershipTier?: T;
  status?: T;
  joinedDate?: T;
  renewalDate?: T;
  stripeCustomerId?: T;
  xeroContactId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  name?: T;
  annualPrice?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  displayOrder?: T;
  stripePriceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  purchaserName?: T;
  purchaserEmail?: T;
  event?: T;
  ticketType?: T;
  quantity?: T;
  contact?: T;
  stripePaymentIntentId?: T;
  totalAmount?: T;
  serviceFeeAmount?: T;
  taxAmount?: T;
  status?: T;
  qrToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  entityType?: T;
  entityId?: T;
  action?: T;
  fromState?: T;
  toState?: T;
  actorId?: T;
  actorType?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Small links shown in the top bar (e.g., "Become a Member", "Member Login", "Contact"). Social icons are pulled automatically from Site Settings.
   */
  utilityNav?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Primary site navigation. Each item can optionally have dropdown child links.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Optional child links shown in a dropdown menu under this item.
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Organize footer links into columns with headings. Contact info and social links appear automatically from Site Settings.
   */
  columns?:
    | {
        /**
         * Column heading (e.g., "Quick Links", "Resources", "Events")
         */
        heading: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright text shown at the bottom of the footer. Use {year} and it will be replaced with the current year automatically.
   */
  copyright?: string | null;
  /**
   * Legacy flat nav links. Use Footer Columns instead.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage your site branding, contact information, social links, and theme colors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Displayed in the browser tab and fallback header text.
   */
  siteName: string;
  /**
   * Main site logo. Recommended: SVG or transparent PNG, at least 200px wide.
   */
  logo?: (number | null) | Media;
  /**
   * A short tagline shown below the logo or in the hero area.
   */
  tagline?: string | null;
  /**
   * Currency used for all pricing — membership tiers, event tickets, etc. All amounts are stored in minor units (e.g., cents) and displayed in the chosen currency.
   */
  currency: 'CAD' | 'USD';
  /**
   * Full mailing address. Line breaks are preserved.
   */
  address?: string | null;
  /**
   * Main phone number (displayed as-is).
   */
  phone?: string | null;
  /**
   * General contact email address.
   */
  email?: string | null;
  /**
   * Add links to your social media profiles.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok';
        /**
         * Full URL (e.g., https://facebook.com/yourchamber)
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main brand color (hex). Used for headers, buttons, and accents.
   */
  primaryColor: string;
  /**
   * Secondary brand color (hex). Used for hover states and backgrounds.
   */
  secondaryColor: string;
  /**
   * Accent color (hex). Used for highlights and call-to-action buttons.
   */
  accentColor: string;
  /**
   * Font family for headings (h1–h6).
   */
  headingFont:
    | 'system-ui, -apple-system, sans-serif'
    | 'var(--font-geist-sans), sans-serif'
    | "'Inter', sans-serif"
    | "'Lora', serif"
    | "'Merriweather', serif"
    | "var(--font-montserrat), 'Montserrat', sans-serif"
    | "'Open Sans', sans-serif"
    | "'Playfair Display', serif"
    | "'Raleway', sans-serif"
    | "'Roboto', sans-serif";
  /**
   * Font family for body text.
   */
  bodyFont:
    | 'system-ui, -apple-system, sans-serif'
    | 'var(--font-geist-sans), sans-serif'
    | "'Inter', sans-serif"
    | "'Lora', serif"
    | "'Merriweather', serif"
    | "var(--font-montserrat), 'Montserrat', sans-serif"
    | "'Open Sans', sans-serif"
    | "'Playfair Display', serif"
    | "'Raleway', sans-serif"
    | "'Roboto', sans-serif";
  /**
   * Google Analytics 4 measurement ID (e.g., G-XXXXXXXXXX). Leave empty to disable.
   */
  gaId?: string | null;
  /**
   * GTM container ID (e.g., GTM-XXXXXXX). Leave empty to disable.
   */
  gtmId?: string | null;
  /**
   * Custom HTML/scripts injected into <head>. Use for third-party tracking pixels, meta tags, etc. Be careful — bad scripts can break the site.
   */
  customHeadScripts?: string | null;
  /**
   * Name of the applicable tax (e.g., "HST", "GST", "VAT"). Leave blank if no tax applies.
   */
  taxName?: string | null;
  /**
   * Tax percentage applied to ticket price + service fee (e.g., enter 15 for 15% HST). Set to 0 to disable.
   */
  taxRate?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  utilityNav?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  tagline?: T;
  currency?: T;
  address?: T;
  phone?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  headingFont?: T;
  bodyFont?: T;
  gaId?: T;
  gtmId?: T;
  customHeadScripts?: T;
  taxName?: T;
  taxRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}